name: "Design Impact Report \U0001F680"
description: "File a design report to improve DIPY design"
labels: ["type:refactoring"]
body:
  - type: markdown
    attributes:
      value: |
        **Please review [our guidelines to post an issue](https://github.com/dipy/dipy/discussions/3585) before opening a new issue.**

  - type: textarea
    attributes:
      label: Summary
      description: |
        Description of the impact of the current design in terms of ease-of-use, or intuitiveness, and how a change in
        design would benefit the toolkit, including a minimal reproducible example.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Impact analysis
      description: |
        Analysis of the benefits/downsides of the current design, and the benefits/downsides of the proposed design.
    validations:
      required: false

  - type: input
    attributes:
      label: DIPY version
      description: What version of DIPY are you using? (e.g. `pip show dipy`)
      placeholder: e.g., dipy 1.11.0 (or 2cec3c8 if a commit is appropriate)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Any additional information, configuration or data that might be necessary to reproduce the issue.
    validations:
      required: false
