name: "Coverage Improvement Report \U0001F3AF"
description: "File a coverage report to improve code coverage in DIPY"
labels: ["type:coverage"]
body:
  - type: markdown
    attributes:
      value: |
        **Please review [our guidelines to post an issue](https://github.com/dipy/dipy/discussions/3585) before opening a new issue.**

  - type: textarea
    attributes:
      label: Summary
      description: |
        A clear and concise description of the impact of the current coverage in a given module, and how an increased
        coverage would benefit the toolkit.
    validations:
      required: true

  - type: input
    attributes:
      label: DIPY version
      description: What version of DIPY are you using? (e.g. `pip show dipy`)
      placeholder: e.g., dipy 1.11.0 (or 2cec3c8 if a commit is appropriate)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Any additional information, configuration or data that might be necessary to reproduce the issue.
    validations:
      required: false
