name: "Coding Style Inconsistency Report \U0001F4DD"
description: "File a coding style report to improve consistency in DIPY"
labels: ["type:style"]
body:
  - type: markdown
    attributes:
      value: |
        **Please review [our guidelines to post an issue](https://github.com/dipy/dipy/discussions/3585) before opening a new issue.**

  - type: textarea
    attributes:
      label: Summary
      description: |
        A clear and concise description of the coding style inconsistency, and what the consistent style should be
        according to the DIPY Coding Style Guidelines (https://docs.dipy.org/stable/devel/coding_style_guideline.html).
    validations:
      required: true

  - type: input
    attributes:
      label: DIPY version
      description: What version of DIPY are you using? (e.g. `pip show dipy`)
      placeholder: e.g., dipy 1.11.0 (or 2cec3c8 if a commit is appropriate)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Any additional information, configuration or data that might be necessary to reproduce the issue.
    validations:
      required: false
