name: Label PRs

on:
  - pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: srvaroa/labeler@v1.13.0
      env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
